name: Build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore Xbox360_USB_Explorer.slnx

      - name: Build solution
        run: msbuild Xbox360_USB_Explorer.slnx /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Xbox360_USB_Explorer
          path: Xbox360_USB_Explorer/bin/Release/
